debug: false

sentry:
  user: "pepe"
  password: "pepe"
  url: "url"

mongo:
  ip: "mlab"
  port: "27017"
  database: "qalorie-staging"
  uri: "mongodb://qalorie-prod:G4KvaFjudfxcdf8E@ds025658-a0.mlab.com:25658,ds025658-a1.mlab.com:25658/qalorie-prod?replicaSet=rs-ds025658"
app:
  baseUrl: "http://qalorie.com"
  domain: "qalorie.com"
  host: "localhost"
  port: 3000

auth:
  auth_token_secret: 'bf5fb423-a9af-4494-9ee0-234f707f4457'

facebook:
  client_id: '1577823505867388'
  client_secret: 'c619acd8c6712a0015aa172d04fb857b'
  callback_url: 'http://qalorie.com/auth/facebook/callback'

sendgrid:
  app_id: 'qalorie-app'
  secret_id: 'tzP6RKFDFXmADRJC'
  recover_id: '36640625-93bc-4628-a8ef-2c596addd583'
  welcome_id: '8b0a29a7-a353-4ffd-af22-36096d359429'
  delete_id:  'b2d0455b-305f-4986-a16f-7a0d72c496f5'
  support_id:  '9cbbff61-d340-4a9b-b561-55bd547d7837'
  ft_upgrade_id:  '3626efa0-9f33-4574-b561-e43cec5336bc'

stripe:
  private_key: 'sk_live_sbK5tA2jFVFs4wrmeG1SoE5l'
  public_key: 'pk_live_Ci82U5dp54K2M2Dzgmqk4bSG'

  plans:
    trial:
      id: 'trial_plan'
      amount: 2995
      name: 'Free Trial'

    monthly:
      id: 'monthly_plan'
      amount: 2995
      name: 'Monthly'

    yearly:
      id: 'yearly_plan'
      amount: 29950
      name: 'Yearly'

  products:
    appointments:
      id: '1_app'
      discount:
        4: 0
        6: 2995
        1: 0
        2: 0
        12: 8985


emails:
  sender_name: 'Qalorie'
  sender: 'service@qalorie.com'
  support: 'ticket@qalorie.com'
